pipeline{
  agent any
  
  tools{
    maven 'maven 3.6.1'
  }
  
  stages{
    stage('build'){
      steps{
        echo 'compiling worker app'
        dir('worker'){
          sh 'mvn compile'
        }
      }
    }
    stage(two){
      steps{
        echo 'running unit test on worker app'
      }
    }
    stage(three){
      steps{
        echo 'packaging worker app'
     }
    }
  }
  post{
    always{
      echo 'Building multibranch pipeline for worker is completed.'
    }
  }
}
