pipeline{
  agent any
  
  tools{
    maven 'maven 3.6.1'
  }
  
  stages{
    stage('build'){
      steps{
        echo 'compiling worker app'
        dir('worker'){
          sh 'mvn compile'
        }
      }
    }
    stage('test'){
      steps{
        echo 'running unit test on worker app'
        dir('worker'){
          sh 'mv clean test'
        }
      }
    }
    stage('package'){
      steps{
        echo 'packaging worker app'
        dir('worker'){
          sh 'maven package'
        }
     }
    }
  }
  post{
    always{
      echo 'Building multibranch pipeline for worker is completed.'
    }
  }
}
