pipeline{
  agent any
  
  tools{
    maven 'maven 3.6.1'
  }
  
  stages{
    stage('build'){
      echo 'compiling worker app'
      dir('worker'){
        sh 'mvn compile'
      }
    }
    stage(two){
      echo 'running unit test on worker app'
    }
    stage(three){
      echo 'packaging worker app'
    }
  }
  post{
    always{
      echo 'Building multibranch pipeline for worker is completed.'
    }
  }
}
